# Agenda
#### 1. Creating new 1D array, type checking, dimension checking and size checking.
#### 2. Creating new 2D array, type checking, dimension checking and size checking.
#### 3. Creating new 3D array, type checking, dimension checking and size checking.

In [1]:
import numpy as np

#### 1. Creating new 1D array, type checking, dimension checking and size checking.

In [9]:
# To create a new 1d array
list1 = [1,2,3,4,5,6,7,8,9,10,11]
ar_1 = np.array(list1)
print(ar_1)
print(type(ar_1))

[ 1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [10]:
# To check dimensions of the array
ar_1.ndim

1

In [11]:
# To check size of the array. How many elements are there in the array.
ar_1.size

11

#### 2. Creating new 2D array, type checking, dimension checking and size checking.

In [14]:
list2 = [[1,2,3,4,5],[1,2,3,4,5]]
ar_2 = np.array(list2)
print(ar_2)
print(type(ar_2))

[[1 2 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>


In [18]:
print(f"Dimension of the array is: ",ar_2.ndim)

Dimension of the array is:  2


In [19]:
print(f"Total elements of the array is: ",ar_2.size)

Total elements of the array is:  10


In [22]:
# To check shape of the of the array.
print(ar_2.shape)
print(f"Shape function is showing the number of row is {ar_2.shape[0]} and column is {ar_2.shape[1]}")

(2, 5)
Shape function is showing the number of row is 2 and column is 5


In [24]:
print(f"Data type of the array 2 is: ",ar_2.dtype)

Data type of the array 2 is:  int32


#### 3. Creating new 3D array, type checking, dimension checking and size checking.

In [36]:
list3 = [[[1,2,3,4]],[[1,2,3,4]],[[1,2,3,4]]]
ar_3 = np.array(list3)
print(ar_3)

[[[1 2 3 4]]

 [[1 2 3 4]]

 [[1 2 3 4]]]


In [39]:
print(f"Datatype of the array is : {ar_3.dtype}")
print(f"Shape of the array is : {ar_3.shape}")
print(f"Dimension of the array is : {ar_3.ndim}")

Datatype of the array is : int32
Shape of the array is : (3, 1, 4)
Dimension of the array is : 3
